# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_jokes.ipynb.

# %% auto 0
__all__ = ['qual_time_nao_tem_mundial']

# %% ../01_jokes.ipynb 3
def qual_time_nao_tem_mundial():
    return "Palmeiras!"

